[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "example"
version = "0.0.1"
description = ""
readme = ""
requires-python = ""
license = { file = "LICENSE" }
keywords = [ ]
dependencies = [ ]

[project.optional-dependencies]
dev = [ ]

[tool.setuptools.package-data]
"example" = [ "py.typed" ]
