/* eslint-disable no-new */
import { Component, Project, SampleDir } from 'projen';

/**
 * Python code sample.
 */
export class PythonBasicSample extends Component {
  constructor(project: Project) {
    super(project);

    // src directory
    new SampleDir(project, 'src/hello_world', {
      files: {
        '__init__.py': '"""Sample package auto generated by projen-python"""',
        'hello_world.py': [
          '"""Says hello to the given name."""',
          'def hello(name: str) -> str:',
          '    """A simple greeting.',
          '    Args:',
          '        name (str): Name to greet.',
          '    Returns:',
          '        str: greeting message',
          '    """',
          '    return f"Hello {name}!"',
          '',
        ].join('\n'),
        'py.typed': '',
      },
    });

    // tests directory
    new SampleDir(project, 'tests/hello_world', {
      files: {
        '__init__.py': '',
        'test_hello_world.py': ['# FIXME ADD TESTS'].join('\n'),
      },
    });
  }
}
