// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".

/**
 * SpikeTypeOptional
 */
export interface SpikeTypeOptional {
  readonly prop3?: number;
  readonly prop2?: number;
  readonly prop1?: string;
}
