name: master-build

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build, lint, test in master branch
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: node
      tooling-version: 20
      target-build: true
      target-lint: true
      target-test-unit: true
      target-test-integration: true
