name: pr-build

on:
  pull_request:
    branches: ['main']

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR
        uses: Namchee/conventional-pr@v0.15.6
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build, lint, test in PR
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: node
      tooling-version: 20
      target-build: true
      target-lint: true
      target-test: true
