name: tag-publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Check package
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: node
      tooling-version: 20
      stage: prd
      target-build: true
      target-lint: true
      target-test: true

  publish-npm:
    name: Publish to npmjs.org
    runs-on: ubuntu-latest
    needs: build
    environment: npmjs-registry
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: make publish-npmjs
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  publish-pypi:
    name: Publish to pypi
    runs-on: ubuntu-latest
    needs: build
    environment: pypi-registry
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: make publish-pypi
        env:
          PYPI_TOKEN_NAME: ${{ secrets.PYPI_TOKEN_NAME }}
          PYPI_TOKEN_PASSWORD: ${{ secrets.PYPI_TOKEN_PASSWORD }}
